Select
EKBE.MANDT as Client_Id
,EKBE.EBELN as Purchasing_Document_Id
,EKBE.EBELP as Purchasing_Document_Item_Id
,EKBE.ZEKKN as Seq_No_Account_Assgt_Id
,EKBE.VGABE as Trans_Event_Type_Id
,EKBE.GJAHR as Material_Document_Year_Id
,EKBE.BELNR as Material_Document_Id
,EKBE.BUZEI as Item_In_Material_Document_Id
,EKBE.BEWTP as Purchase_Order_History_Category_Id
,EKBE.BWART as Movement_Type_Id
,{{ date_case_gen('EKBE.BUDAT','Posting_In_The_Document_Date')}}
,EKBE.MENGE as Qty
,EKBE.BPMNG as Quantity_In_Opun
,EKBE.DMBTR as Loccur_Amount
,EKBE.WRBTR as Amount_Document_Currency_Val
,EKBE.WAERS as Currency_Id
,EKBE.AREWR as Gr_Ir_Clearg_Local_Currency_Val
,EKBE.WESBS as Gr_Blck_Stock_In_Oun
,EKBE.BPWES as Gr_Blocked_Stck_Opun
,EKBE.SHKZG as Debitcredit_Indicator
,EKBE.BWTAR as Valuation_Type_Id
,EKBE.ELIKZ as Delivery_Completed
,EKBE.XBLNR as Reference_Document_Number
,EKBE.LFGJA as Fisc_Year_Ref_Doc
,EKBE.LFBNR as Reference_Document
,EKBE.LFPOS as Item_Reference_Document
,EKBE.GRUND as Reason_Movement_Id
,{{ date_case_gen('EKBE.CPUDT','Entry_Date')}}
,EKBE.CPUTM as Entry_Tim
,EKBE.REEWR as Voice_Val
,EKBE.EVERE as Compliance_With_Shipping_Instr_Id
,EKBE.REFWR as Voice_Fc_Val
,EKBE.MATNR as Material_Id
,EKBE.WERKS as Plant_Id
,EKBE.XWSBR as Revgr_Despite_Ir
,EKBE.ETENS as Sequential_Number
,EKBE.KNUMV as Document_Condition_No
,EKBE.MWSKZ as Tax_Code_Id
,EKBE.LSMNG as Del_Note_Quantity
,EKBE.LSMEH as Delivery_Note_Uom_Id
,EKBE.EMATN as Material_Number_Id
,EKBE.AREWW as Gr_Ir_Clearg_Fc_Val
,EKBE.HSWAE as Local_Currency_Key_Id
,EKBE.BAMNG as BAMNG
,EKBE.CHARG as Batch_Id
,{{ date_case_gen('EKBE.BLDAT','Document_In_Document_Date')}}
,EKBE.XWOFF as Calculation_Val_Open
,EKBE.XUNPL as Unplanned_Acct_Assgmt_Inv_Verification
,EKBE.ERNAM as Created_By
,EKBE.SRVPOS as Service_Number_Id
,EKBE.PACKNO as Package_Number_Service_Id
,EKBE.INTROW as Line_Number_Service
,EKBE.BEKKN as Number_Po_Account_Assignment
,EKBE.LEMIN as Returns_Indicator
,EKBE.AREWB as AREWB
,EKBE.REWRB as Voice_Amount_Po_Currency_Val
,EKBE.SAPRL as Sap_Release
,EKBE.MENGE_POP as MENGE_POP
,EKBE.BPMNG_POP as BPMNG_POP
,EKBE.DMBTR_POP as DMBTR_POP
,EKBE.WRBTR_POP as WRBTR_POP
,EKBE.WESBB as Val_Gr_Blocked_Stock_In_Oun
,EKBE.BPWEB as Valuated_Gr_Blocked_Stock_In_Opun
,EKBE.WEORA as Acceptance_At_Origin
,EKBE.AREWR_POP as AREWR_POP
,EKBE.KUDIF as Exchange_Rate_Difference_Amount_Val
,EKBE.RETAMT_FC as Retention_Document_Currency_Val
,EKBE.RETAMT_LC as Retention_Company_Code_Currency_Val
,EKBE.RETAMTP_FC as Posted_Retention_Document_Currency_Val
,EKBE.RETAMTP_LC as Posted_Security_Retention_Cc_Crcy_Val
,EKBE.XMACC as Multiple_Account_Assignment
,EKBE.WKURS as Exchange_Rate
,EKBE.INV_ITEM_ORIGIN as Origin_An_Invoice_Item
,EKBE.VBELN_ST as Delivery_Id
,EKBE.VBELP_ST as Delivery_Item_Id
,EKBE.SGT_SCAT as Stock_Segment
,EKBE.ET_UPD as Slqupd
,EKBE.J_SC_DIE_COMP_F as Depreciation_Completion_Flag
,EKBE.FSH_SEASON_YEAR as Season_Year
,EKBE.FSH_SEASON as Season_Id
,EKBE.FSH_COLLECTION as Fashion_Collection
,EKBE.FSH_THEME as Fashion_Theme
,EKBE.WRF_CHARSTC1 as Characteristic_Value_1
,EKBE.WRF_CHARSTC2 as Characteristic_Value_2
,EKBE.WRF_CHARSTC3 as Characteristic_Value_3
,EKBE._FIVETRAN_DELETED as _Fivetran_Deleted
,EKBE._FIVETRAN_SYNCED as _Fivetran_Synced
from {{source('dhsaphana1_sapabap1', 'ekbe')}}
where
EKBE.MANDT in '800'