Select
VBAK.MANDT as Client_Id
,VBAK.VBELN as Sales_Document_Id
,VBAK.KOSTL as Cost_Center_Id
,VBAK.MAHZA as Number_Contacts
,VBAK.MSR_ID as Process_Identification_Number
,VBAK._DATAAGING as Filter_Value_Aging_Date
,VBAK.TAXK5 as Taxclass5_Cust_Id
,VBAK.KVGR4 as Customer_Group_4_Id
,VBAK.AMTBL as Rel_Credit_Val
,VBAK.TRVOG as Transaction_Group
,VBAK.HB_RESDATE as Resolution_Date
,VBAK.FMBDAT as Material_Availability_Date
,VBAK.FSH_VRSN_STATUS as Snapshot_Status
,VBAK.UPD_TMSTMP as Time_Stamp
,VBAK.AUART as Sales_Document_Type_Id
,VBAK.HB_EXPDATE as Expiration_Date
,VBAK.SCHEME_GRP as Group_Ref_Procedure_Id
,VBAK.SMENR as Number_Sales_Unit_Id
,VBAK.TAXK6 as Taxclass6_Cust_Id
,VBAK.FSH_TRANSACTION as Transaction_Number
,VBAK.KVGR5 as Customer_Group_5_Id
,VBAK.GSKST as Business_Area_From_Cost_Center_Id
,VBAK.VKGRP as Sales_Group_Id
,VBAK.PAY_METHOD as Payment_Methods
,VBAK.KTEXT as Search_Term_Product_Proposal
,VBAK.PS_PSP_PNR as Wbs_Element_Id
,VBAK.FAKSK as Billing_Block_In_Sd_Document_Id
,VBAK.BNDDT as Quotation_Valid_To_Date
,VBAK.CMWAE as Currency_Id
,VBAK.KOKRS as Controlling_Area_Id
,VBAK.KUNNR as Sold_To_Party_Id
,VBAK.BETC as Business_Event_Type_Code
,VBAK.FSH_REREG as Release_Rule_Id
,VBAK.TAS as Treasury_Account_Symbol
,VBAK.CANCEL_ALLOW as Cancellation_Allowed
,VBAK.FKARA as Order_Rel_Bill_Type_Id
,VBAK.TAXK7 as Taxclass7_Cust_Id
,VBAK.GWLDT as Guarantee_Date
,VBAK.PSM_BUDAT as Posting_In_The_Document_Date
,VBAK.OBJNR as Object_Number_At_Header_Level_Id
,VBAK.AUTLF as Complete_Delivery
,VBAK.STWAE as Statistics_Currency_Id
,VBAK.ABHOV as Pick_Up_Tim
,VBAK.LOGSYSB as Logical_System_Id
,VBAK.FSH_KVGR6 as Customer_Group_6_Id
,VBAK.BNAME as Name_Orderer
,VBAK.TAXK8 as Taxclass8_Cust_Id
,VBAK.XBLNR as Reference_Document_Number
,VBAK.MTLAUR as Marker_Low_Income_Housing_Id
,VBAK.AUGRU as Order_Reason_Id
,VBAK.STAFO as Update_Group_Stats_Id
,VBAK.SWENR as Business_Entity_Number_Id
,VBAK._XLSO_TRANS_CTXT as _Xlso_Trans_Ctxt
,VBAK.ABRUF_PART as Check_Partner_Authorizations
,VBAK.CMNGV as Next_Date
,VBAK.KNKLI as Credit_Account_Id
,VBAK.SPART as Division_Id
,VBAK.PROLI as Dg_Mgmt_Profile_Id
,VBAK.ENQUEUE_GRP as Enqueue_Grp
,VBAK.VZEIT as Requested_Dely_Tim
,VBAK.KALCD as Proc_Camp_Determin_Id
,VBAK.BUKRS_VF as Company_Code_To_Be_Billed_Id
,VBAK.FSH_KVGR7 as Customer_Group_7_Id
,VBAK.VPRGR as Proposed_Date_Type
,VBAK.CRM_GUID as Character_Field_Length_70
,VBAK.HITYP_PR as Hierarchy_Type_Pricing_Id
,VBAK.TAXK9 as Taxclass9_Cust_Id
,VBAK.VGBEL as Reference_Document_Id
,VBAK.ERZET as Created_Tim
,VBAK.IHREZ as Your_Reference
,VBAK.SUBMI as Collective_Number_Sd
,VBAK.VDATU as Requested_Delivery_Date
,VBAK._XLSO_VARIANT_ID as _Xlso_Variant_Id
,VBAK.ABDIS as Mrp_Delivery_Schedule_Types
,VBAK.FSH_KVGR8 as Customer_Group_8_Id
,VBAK.ERNAM as Created_By
,VBAK.HB_CONT_REASON as Contingency_Id
,VBAK.NETWR as Net_Val
,VBAK.VBKLA as Original_System
,VBAK.VGTYP as Preceding_Doc_Categ
,VBAK.SBGRP as Credit_Rep_Group_Id
,VBAK.STCEG_L as Tax_Destination_Country_Id
,VBAK.FSH_KVGR10 as Customer_Group_10_Id
,VBAK.KNUMA as Agreement_Id
,VBAK.FSH_SS as Order_Scheduling_Strategy_Id
,VBAK.FSH_CQ_CHECK as Requirement_Relevant
,VBAK.XEGDR as Eu_Triangular_Deal
,VBAK.BSTNK as Customer_Purchase_Order_Number
,VBAK.MULTI as Multiple_Promotions
,VBAK.SPPAYM as Payment_Method
,VBAK.LIFSK as Delivery_Block_Document_Header_Id
,VBAK.FSH_KVGR9 as Customer_Group_9_Id
,VBAK.AEDAT as Changed_Date
,VBAK.WTYSC_CLM_HDR as Claim_Header
,VBAK.DAT_FZAU as Cml_Delivery_Order_Qty_Date
,VBAK.AWAHR as Sales_Probability
,VBAK.KURST as Exchange_Rate_Type_Id
,VBAK.GUEEN as Valid_To_Date
,VBAK._XLSO_SO_VALD_TO as _Xlso_So_Vald_To
,VBAK.CMNUP as Next_Check_Date
,VBAK.ABHOD as Pick_Up_Date
,VBAK.VKORG as Sales_Organization_Id
,VBAK.AUDAT as Document_Date
,VBAK.ZUONR as Assignment_Number
,VBAK.ANGDT as Quotation_Inquiry_Is_Valid_From_Date
,VBAK.VSBED as Shipping_Conditions_Id
,VBAK._XLSO_PAYMENT_OP as _Xlso_Payment_Op
,VBAK.REP_FREQ as Reporting_Frequency
,VBAK.HANDLE as Int_Id
,VBAK._XLSO_SO_VALD_FM as _Xlso_So_Vald_Fm
,VBAK.BSTZD as Purchase_Order_Number_Supplement
,VBAK.TAXK1 as Alternative_Tax_Classification_Id
,VBAK.MAHDT as Last_Customer_Contact_Date
,VBAK.BSTDK as Customer_Purchase_Order_Date
,VBAK.VBELN_GRP as Mster_Contract_Number_Id
,VBAK.HANDOVERLOC as Handover_Location
,VBAK.QMNUM as Notification_Id
,VBAK.KALSM_CH as Search_Procedure_Id
,VBAK.CONT_DG as Contains_Dg
,VBAK.CMFRE as Release_Date
,VBAK.VTWEG as Distribution_Channel_Id
,VBAK.TELF1 as Telephone_Number
,VBAK.AUFNR as Order_Id
,VBAK.PHASE as Sales_Phase_Id
,VBAK.TAXK2 as Taxclass2_Cust_Id
,VBAK.KVGR1 as Customer_Group_1_Id
,VBAK.GRUPP as Customer_Credit_Group_Id
,VBAK.FSH_OS_STG_CHANGE as Os_Strategy_Specific_Fields_Change
,VBAK.ABHOB as ABHOB
,VBAK.LANDTX as Tax_Departure_Country_Id
,VBAK.KALSM as Pricing_Procedure_Id
,VBAK.ERDAT as Created_Date
,VBAK.BPN as Business_Partner_Number_Id
,VBAK.STAGE as Construction_Stage
,VBAK.KKBER as Credit_Control_Area_Id
,VBAK.TAXK3 as Taxclass3_Cust_Id
,VBAK.ABRVW as Usage_Id
,VBAK.VBTYP as Sd_Document_Category
,VBAK.KVGR2 as Customer_Group_2_Id
,VBAK.KNUMV as Document_Condition_No
,VBAK.GUEBG as Valid_From_Date
,VBAK.FSH_VAS_CG as Vas_Customer_Group_Id
,VBAK.WAERK as Sd_Document_Currency_Id
,VBAK.VKBUR as Sales_Office_Id
,VBAK.CTLPC as Credit_Management_Risk_Category_Id
,VBAK.VSNMR_V as Sales_Document_Version_Number
,VBAK.RPLNR as Number_Payment_Card_Plan_Type_Id
,VBAK.VBKLT as Sd_Document_Indicator
,VBAK.MOD_ALLOW as Modification_Allowed
,VBAK.TAXK4 as Tax_Classification_4_Customer_Id
,VBAK._XLSO_CATALOG_ID as _Xlso_Catalog_Id
,VBAK.KVGR3 as Customer_Group_3_Id
,VBAK.FSH_CANDATE as Cancellation_Date
,VBAK.AGRZR as Accrual_Period
,VBAK.MILL_APPL_ID as Application_Id
,VBAK.BSARK as Customer_Purchase_Order_Type_Id
,VBAK.TM_CTRL_KEY as Control_Key
,VBAK.GSBER as Business_Area_Id
,VBAK._FIVETRAN_DELETED as _Fivetran_Deleted
,VBAK._FIVETRAN_SYNCED as _Fivetran_Synced
from {{source('dhsaphana1_sapabap1', 'vbak')}}
where
VBAK.MANDT in ('800')