Select
VBUP.MANDT as Client_Id
,VBUP.POSNR as Sd_Item_Id
,VBUP.VBELN as Sales_Document_Id
,VBUP.UVPAK as Item_Packaging
,VBUP.UVVLK as Item_Deliv
,VBUP.MILL_VS_VSSTA as Status_Sales_Order_Item
,VBUP.PKSTA as Packing_Status_Item
,VBUP.LSSTA as Delivery_Block_Status_Item
,VBUP.VLSTP as Decentralized_Whse_Processing
,VBUP.ABSTA as Rejection_Status_Sd_Item
,VBUP.FKSTA as Billing_Status
,VBUP.FKIVP as Intercompany_Billing_Status
,VBUP.LFGSA as Overall_Deliv_Status
,VBUP.RRSTA as Revenue_Determination_Status
,VBUP.LFSTA as Delivery_Status
,VBUP.FKSAA as Ord_Related_Bill_St
,VBUP.WBSTA as Goods_Movement_Status
,VBUP.LTSPS as Stockable_Type_Switched_Into_Stand_Prod
,VBUP.COSTA as Confirmation_Status_Ale
,VBUP.FSSTA as Billing_Block_Status_Items
,VBUP.KOSTA as Picking_Status_Putaway_Status
,VBUP.UVPIK as Item_Picking_Putaway
,VBUP.UVFAK as Item_Billing
,VBUP.UVALL as Item
,VBUP.RFGSA as Overall_Status_Reference
,VBUP.UVPRS as Pricing_Item_Is_Incomplete
,VBUP.LVSTA as Wm_Activity_Status
,VBUP.RFSTA as Reference_Status
,VBUP.CMPPJ as Expt_Cred_Insurance
,VBUP.CMPPI as Financial_Document
,VBUP.HDALL as Delivery_Item_Not_Complete
,VBUP.BESTA as Confirmed
,VBUP.PDSTA as Pod_Status_On_Item_Level
,VBUP.FSH_AR_STAT_ITM as Arun_Status_Item_Level
,VBUP.MANEK as Manual_Completion_Contract
,VBUP.GBSTA as Overall_Status
,VBUP.UVWAK as Item_Goods_Mvmt
,VBUP.DCSTA as Delay_Status
,VBUP.UVP05 as Customer_Reserves_5_Item_Status
,VBUP.UVP02 as Customer_Reserves_2_Item_Status
,VBUP.UVP04 as Item_Reserves_4_Item_Status
,VBUP.KOQUA as Pick_Confirmation
,VBUP.UVP01 as Customer_Reserves_1_Item_Status
,VBUP.UVP03 as Item_Reserves_3_Item_Status
,VBUP._FIVETRAN_DELETED as _Fivetran_Deleted
,VBUP._FIVETRAN_SYNCED as _Fivetran_Synced
from {{source('dhsaphana1_sapabap1', 'vbup')}}
where
VBUP.MANDT in '800'