Select
LFA1.MANDT as Client_Id
,LFA1.LIFNR as Vendor_Id
,LFA1.LAND1 as Country_Key_Id
,LFA1.NAME1 as Name
,LFA1.NAME2 as Name_2
,LFA1.NAME3 as Name_3
,LFA1.NAME4 as Name_4
,LFA1.ORT01 as City
,LFA1.ORT02 as District
,LFA1.PFACH as Po_Box
,LFA1.PSTL2 as P_O_Box_Postal_Code
,LFA1.PSTLZ as Postal_Code
,LFA1.REGIO as Region_Id
,LFA1.SORTL as Sort_Field
,LFA1.STRAS as Street_And_House_Number
,LFA1.ADRNR as Address_Id
,LFA1.MCOD1 as Search_Term_Matchcode_Search
,LFA1.MCOD2 as MCOD2
,LFA1.MCOD3 as MCOD3
,LFA1.ANRED as Title
,LFA1.BAHNS as Train_Station
,LFA1.BBBNR as Int_Location_No_1
,LFA1.BBSNR as Int_Location_No_2
,LFA1.BEGRU as Authorization_Group_Id
,LFA1.BRSCH as Industry_Key_Id
,LFA1.BUBKZ as Check_Digit
,LFA1.DATLT as Communication_Line_No
,LFA1.DTAMS as Dme_Indicator
,LFA1.DTAWS as Instruction_Key_Id
,{{ date_case_gen('LFA1.ERDAT','Created_On_Date')}}
,LFA1.ERNAM as Created_By
,LFA1.ESRNR as Por_Subscriber_Number
,LFA1.KONZS as Group_Key
,LFA1.KTOKK as Vendor_Account_Group_Id
,LFA1.KUNNR as Customer_Id
,LFA1.LNRZA as Alternative_Payee_Id
,LFA1.LOEVM as Central_Deletion_Flag
,LFA1.SPERR as Central_Posting_Block
,LFA1.SPERM as Central_Purchasing_Block
,LFA1.SPRAS as Language_Key_Id
,LFA1.STCD1 as Tax_Number_1
,LFA1.STCD2 as Tax_Number_2
,LFA1.STKZA as Sales_Equalizatn_Tax
,LFA1.STKZU as Liable_Vat
,LFA1.TELBX as Telebox_Number
,LFA1.TELF1 as Telephone_1
,LFA1.TELF2 as Second_Telephone_Number
,LFA1.TELFX as Fax_Number
,LFA1.TELTX as Teletex_Number
,LFA1.TELX1 as Telex_Number
,LFA1.XCPDK as One_Time_Account
,LFA1.XZEMP as Payee_In_Document
,LFA1.VBUND as Trading_Partner_Id
,LFA1.FISKN as Fiscal_Address_Id
,LFA1.STCEG as Vat_Registration_No
,LFA1.STKZN as Natural_Person
,LFA1.SPERQ as Function_That_Will_Be_Blocked_Id
,LFA1.GBORT as Place_Birth
,{{ date_case_gen('LFA1.GBDAT','Birth_Date')}}
,LFA1.SEXKZ as Sex
,LFA1.KRAUS as Credit_Information_Number
,{{ date_case_gen('LFA1.REVDB ','Last_Review_External_Date')}}
,LFA1.QSSYS as Vendors_Qm_System_Id
,LFA1.KTOCK as Reference_Acct_Group_Id
,LFA1.PFORT as Po_Box_City
,LFA1.WERKS as Plant_Own_Or_External_Id
,LFA1.LTSNA as Vendor_Sub_Range_Relevant
,LFA1.WERKR as Indicator_Plant_Level_Relevant
,LFA1.PLKAL as Factory_Calendar_Id
,LFA1.DUEFL as Status_Transfer_To_Next_Release
,LFA1.TXJCD as Tax_Jurisdiction_Id
,LFA1.SPERZ as Payment_Block
,LFA1.SCACD as Standard_Carrier_Access_Code
,LFA1.SFRGR as Forwarding_Agent_Freight_Group_Id
,LFA1.LZONE as Transportation_Zone_Id
,LFA1.XLFZA as Accts_Alt_Payee
,LFA1.DLGRP as Service_Agent_Procedure_Group_Id
,LFA1.FITYP as Tax_Type_Id
,LFA1.STCDT as Tax_Number_Type_Id
,LFA1.REGSS as Registered_Social_Insurance
,LFA1.ACTSS as Social_Ins_Code_Id
,LFA1.STCD3 as Tax_Number_3
,LFA1.STCD4 as Tax_Number_4
,LFA1.STCD5 as Tax_Number_5
,LFA1.IPISP as Tax_Split
,LFA1.TAXBS as Tax_Base_In_Percentage
,LFA1.PROFS as Profession
,LFA1.STGDL as Stat_Grp_Service_Agent_Id
,LFA1.EMNFR as Ext_Manufacturer
,LFA1.LFURL as Uniform_Resource_Locator
,LFA1.J_1KFREPRE as Name_Representative
,LFA1.J_1KFTBUS as Type_Business_Id
,LFA1.J_1KFTIND as Type_Industry_Id
,LFA1.CONFS as Confirmation_Status
,{{ date_case_gen('LFA1.UPDAT','Confirmation_Date')}}
,LFA1.UPTIM as Last_Change_Confirmation_Tim
,LFA1.NODEL as Central_Del_Block
,{{ date_case_gen('LFA1.QSSYSDAT','Validity_Certification_Date')}}
,LFA1.PODKZB as Relevant_Pod
,LFA1.FISKU as Tax_Office_Responsible_Id
,LFA1.STENR as Tax_Number_At_Responsible_Tax_Authority
,LFA1.CARRIER_CONF as Carrier_Confirmation_Is_Expected
,LFA1.MIN_COMP as Micro_Company_Indicator
,LFA1.TERM_LI as Terms_Liability
,LFA1.CRC_NUM as Crc_Number
,LFA1.CVP_XBLCK as Business_Purpose_Completed_Flag
,LFA1.RG as Rg_Number
,LFA1.EXP as Issued_By
,LFA1.UF as State
,{{ date_case_gen('LFA1.RGDATE','Rg_Issuing_Date')}}
,LFA1.RIC as Ric_Number
,LFA1.RNE as Foreign_National_Registration
,{{ date_case_gen('LFA1.RNEDATE','Rne_Issuing_Date')}}
,LFA1.CNAE as Cnae_Id
,LFA1.LEGALNAT as Legal_Nature_Id
,LFA1.CRTN as Crt_Number
,LFA1.ICMSTAXPAY as Icms_Taxpayer_Id
,LFA1.INDTYP as Industry_Main_Type_Id
,LFA1.TDT as Tax_Declaration_Type_Id
,LFA1.COMSIZE as Company_Size_Id
,LFA1.DECREGPC as Declaration_Regimen_Pis_Cofins_Id
,LFA1.J_SC_CAPITAL as Capital_Amount_Val
,LFA1.J_SC_CURRENCY as Currency_Id
,LFA1.ALC as Agency_Location_Code_Id
,LFA1.PMT_OFFICE as Payment_Office_Id
,LFA1.PPA_RELEVANT as Vendor_Is_Ppa_Relevant
,LFA1.PSOFG as Processor_Group_Id
,LFA1.PSOIS as Slaprepr_Proced
,LFA1.PSON1 as PSON1
,LFA1.PSON2 as PSON2
,LFA1.PSON3 as PSON3
,LFA1.PSOVN as First_Name
,LFA1.PSOTL as PSOTL
,LFA1.PSOHS as House_Number
,LFA1.PSOST as Street
,LFA1.TRANSPORT_CHAIN as Transportation_Chain_Id
,LFA1.STAGING_TIME as Staging_Time_In_Days
,LFA1.SCHEDULING_TYPE as Scheduling_Procedure
,LFA1.SUBMI_RELEVANT as Cd_Relevant_Collective_Numbering
,LFA1._FIVETRAN_DELETED as _Fivetran_Deleted
,LFA1._FIVETRAN_SYNCED as _Fivetran_Synced
from {{source('dhsaphana1_sapabap1', 'lfa1')}}
where
LFA1.MANDT in ('800')